# Generated by Django 4.1.7 on 2024-01-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team", name="name", field=models.CharField(max_length=10),
        ),
    ]
